.config/dotnet-tools.json
CodeMirror6/CodeMirror6Wrapper.razor
CodeMirror6/CodeMirrorJsInterop.cs
CodeMirror6/NodeLib/package-lock.json
CodeMirror6/NodeLib/package.json
CodeMirror6/NodeLib/src/CmInstance.ts
CodeMirror6/NodeLib/src/index.ts
Examples.Common/Example.razor
Examples.Common/_Imports.razor

[✨ Implement SetIndentUnit](https://github.com/gaelj/BlazorCodeMirror6/commit/60688247da94b95781465e22a22e3d23c58c3c20)
[✨ Implement initial and dynamic setting of placeholder text](https://github.com/gaelj/BlazorCodeMirror6/commit/b4d10269d8f1fef7510d7a36b4673f2d8c132cea)
[✨ Allow binding to selection ranges](https://github.com/gaelj/BlazorCodeMirror6/commit/0a7b9123546311f3e0630bfe95835c775743c68f)
[⬆️ Run npm update](https://github.com/gaelj/BlazorCodeMirror6/commit/a06170129cef992457f138d8f661d55a27b97888)

Initial development

---

CodeMirror6/CodeMirror6Wrapper.razor.css
CodeMirror6/Models/CodeMirrorLanguage.cs
CodeMirror6/NodeLib/package-lock.json
CodeMirror6/NodeLib/package.json
CodeMirror6/NodeLib/src/CmCommands.ts
CodeMirror6/NodeLib/src/CmFileUpload.ts
CodeMirror6/NodeLib/src/CmLanguage.ts
CodeMirror6/NodeLib/src/index.ts
Examples.Common/Example.razor
Examples.Common/Example.razor.Markdown.cs
README.md

@gaelj
[✨ Support mermaid language highlighting](https://github.com/gaelj/BlazorCodeMirror6/pull/50/commits/128023e2003a6aec02297dec321ed419e8262965)
[128023e](https://github.com/gaelj/BlazorCodeMirror6/pull/50/commits/128023e2003a6aec02297dec321ed419e8262965)
@gaelj
[✨ Add undo & redo toolbar buttons, ensure editor focus after command …](https://github.com/gaelj/BlazorCodeMirror6/pull/50/commits/86cb3bd8022939bca2335521b644fa4a9d000840) 
[86cb3bd](https://github.com/gaelj/BlazorCodeMirror6/pull/50/commits/86cb3bd8022939bca2335521b644fa4a9d000840)
@gaelj
[🐛 Write file link at latest cursor location after uploading](https://github.com/gaelj/BlazorCodeMirror6/pull/50/commits/3e5f808645495b8baf78b18ed6bff2318d9fa7f6)

✨ Support mermaid language highlighting

---

CodeMirror6/NodeLib/src/CmDiagrams.ts

[✨ Hide diagram code unless cursor is in range](https://github.com/gaelj/BlazorCodeMirror6/commit/5297b34e36e8bf64c0e3eccd943617895e7a7071)
[✨ Still show the diagram while editing it](https://github.com/gaelj/BlazorCodeMirror6/commit/1331c72edf6e22845a08c509d81d48f9890cc89c)
[✨ Show the diagram code when clicking on the diagram](https://github.com/gaelj/BlazorCodeMirror6/commit/b44e95f470a727c6d149fc170f17bd01d29d2ccc)

Improve diagrams

---

CHANGELOG.md
CodeMirror6/CodeMirror6.csproj
CodeMirror6/CodeMirror6WrapperInternal.razor
CodeMirror6/CodeMirror6WrapperInternal.razor.JsInterop.cs
CodeMirror6/NodeLib/package-lock.json
CodeMirror6/NodeLib/package.json
CodeMirror6/NodeLib/src/index.ts
Examples.BlazorServer/Examples.BlazorServer.csproj
Examples.BlazorServerInteractive/Examples.BlazorServerInteractive.csproj
Examples.BlazorWasm/Examples.BlazorWasm.csproj
Examples.Common/Examples.Common.csproj
NEW_CHANGELOG.md

- Call js module dispose on blazor component dispose
- Update @codemirror/lint
- Ensure the js init of an editor is done only once

Improve init and disposal

---

CHANGELOG.md
CodeMirror6/CodeMirror6.csproj
CodeMirror6/Commands/CMCommandDispatcher.cs
CodeMirror6/Models/CodeMirrorCommandTwoParameters.cs
CodeMirror6/Models/CodeMirrorLanguage.cs
CodeMirror6/Models/CodeMirrorSimpleCommand.cs
CodeMirror6/NodeLib/src/CmColumns.ts
CodeMirror6/NodeLib/src/CmCommands.ts
CodeMirror6/NodeLib/src/CmEmojiView.ts
CodeMirror6/NodeLib/src/CmInstance.ts
CodeMirror6/NodeLib/src/CmKeymap.ts
CodeMirror6/NodeLib/src/CmLanguage.ts
CodeMirror6/NodeLib/src/index.ts
Examples.BlazorServer/Examples.BlazorServer.csproj
Examples.BlazorServerInteractive/Examples.BlazorServerInteractive.csproj
Examples.BlazorWasm/Examples.BlazorWasm.csproj
Examples.Common/Examples.Common.csproj
NEW_CHANGELOG.md

- Add commands to insert markdown table and horizontal rule
- Implement csv and tsv with padded column widths (Does not support multiline cells)
- Add Tab and Shift-Tab keymaps to csv mode, to navigate columns
- Improve eq() of emojiWidget

Implement csv and tsv with padded column widths

---

CHANGELOG.md
CodeMirror6/CodeMirror6.csproj
CodeMirror6/CodeMirror6Wrapper.razor
CodeMirror6/CodeMirror6Wrapper.razor.cs
CodeMirror6/CodeMirror6WrapperInternal.razor
CodeMirror6/CodeMirror6WrapperInternal.razor.cs
CodeMirror6/NodeLib/src/CmColumns.ts
CodeMirror6/NodeLib/src/CmLint.ts
CodeMirror6/NodeLib/src/index.ts
Examples.BlazorServer/Examples.BlazorServer.csproj
Examples.BlazorServerInteractive/Examples.BlazorServerInteractive.csproj
Examples.BlazorWasm/Examples.BlazorWasm.csproj
Examples.Common/Examples.Common.csproj
NEW_CHANGELOG.md
README.md

- Add "Visible" property to allow hiding the editor without destroying it
- Add linting that checks csv column count relative to first line
- Disable initial setting of line wrapping in csv mode
- Fix tabulating csv columns skipped the last / first ones
- Update README

Improve csv mode

---

CHANGELOG.md
CodeMirror6/CodeMirror6.csproj
CodeMirror6/CodeMirror6Wrapper.razor.cs
CodeMirror6/CodeMirror6WrapperInternal.razor
CodeMirror6/CodeMirror6WrapperInternal.razor.cs
CodeMirror6/Models/CodeMirrorSimpleCommand.cs
CodeMirror6/NodeLib/src/CmCommands.ts
CodeMirror6/NodeLib/src/CmDiagrams.ts
CodeMirror6/NodeLib/src/index.ts
Examples.BlazorServer/Examples.BlazorServer.csproj
Examples.BlazorServerInteractive/Examples.BlazorServerInteractive.csproj
Examples.BlazorWasm/Examples.BlazorWasm.csproj
Examples.Common/Example.razor
Examples.Common/Examples.Common.csproj
NEW_CHANGELOG.md

- Implement clipboard commands
- Add no-cors header to diagram requests
- Hide additional content when not visible
- Make visible by default
- Add visibility toggle to example

✨ Implement clipboard commands

---

CodeMirror6/CodeMirror6Wrapper.razor.cs
CodeMirror6/NodeLib/src/CmDiagrams.ts

- Expose CodeMirrorState, for @ref access
- Don't use no-cors header
- Fix menu title in example project

Expose CodeMirrorState, for @ref access

---

CHANGELOG.md
CodeMirror6/CodeMirror6.csproj
CodeMirror6/CodeMirror6Wrapper.razor.cs
CodeMirror6/CodeMirror6WrapperInternal.razor.cs
CodeMirror6/Commands/CMConfigurationSetters.cs
CodeMirror6/Models/CodeMirrorSimpleCommand.cs
CodeMirror6/NodeLib/src/CmColumns.ts
CodeMirror6/NodeLib/src/CmCommands.ts
CodeMirror6/NodeLib/src/CmFileUpload.ts
CodeMirror6/NodeLib/src/index.ts
Examples.BlazorServer/Examples.BlazorServer.csproj
Examples.BlazorServerInteractive/Examples.BlazorServerInteractive.csproj
Examples.BlazorWasm/Examples.BlazorWasm.csproj
Examples.Common/Examples.Common.csproj
NEW_CHANGELOG.md

- Add ClearLocalStorage command
- Paste data copied from Excel formatted as Markdown table
- Fix cursor location on paste was before the pasted text

Paste data copied from Excel formatted as Markdown table

---

CHANGELOG.md
CodeMirror6/CodeMirror6.csproj
CodeMirror6/CodeMirror6WrapperInternal.razor.cs
CodeMirror6/Commands/CMConfigurationSetters.cs
CodeMirror6/NodeLib/src/CmConfiguration.ts
CodeMirror6/NodeLib/src/CmInstance.ts
CodeMirror6/NodeLib/src/index.ts
Examples.BlazorServer/Examples.BlazorServer.csproj
Examples.BlazorServer/Pages/_Host.cshtml
Examples.BlazorServerInteractive/Examples.BlazorServerInteractive.csproj
Examples.BlazorWasm/Examples.BlazorWasm.csproj
Examples.Common/Example.razor
Examples.Common/Examples.Common.csproj
NEW_CHANGELOG.md

- Fix paste button tooltip in example
- Simplify configuration setting interop
- Silence a possible crash on startup

🎨 Simplify configuration setting interop

---

CHANGELOG.md
CodeMirror6/CodeMirror6.csproj
CodeMirror6/CodeMirror6Wrapper.razor
CodeMirror6/CodeMirror6Wrapper.razor.cs
CodeMirror6/CodeMirror6WrapperInternal.razor
CodeMirror6/CodeMirror6WrapperInternal.razor.cs
CodeMirror6/CodeMirror6WrapperInternal.razor.css
CodeMirror6/NodeLib/src/index.ts
Examples.BlazorServer/Examples.BlazorServer.csproj
Examples.BlazorServerInteractive/Examples.BlazorServerInteractive.csproj
Examples.BlazorWasm/Examples.BlazorWasm.csproj
Examples.Common/Example.razor
Examples.Common/Example.razor.css
Examples.Common/Examples.Common.csproj
Examples.Common/Shared/MainLayout.razor.css
NEW_CHANGELOG.md

- Add Height, Width, MaxHeight & MaxWidth parameters
- Implement full screen mode (#109)
- If multiple instances exist on the same page, load the inline css only once
- Add document persistence to LocalStorage to demo

Implement full screen mode (#109)

---

.github/workflows/create-tag-and-deploy-on-merge-to-main.yml
CHANGELOG.md
CodeMirror6/CodeMirror6.csproj
CodeMirror6/CodeMirror6WrapperInternal.razor.cs
CodeMirror6/Models/CodeMirrorConfiguration.cs
CodeMirror6/NodeLib/src/CmConfiguration.ts
CodeMirror6/NodeLib/src/index.ts
Examples.BlazorServer/Examples.BlazorServer.csproj
Examples.BlazorServerInteractive/Examples.BlazorServerInteractive.csproj
Examples.BlazorWasm/Examples.BlazorWasm.csproj
Examples.Common/Example.razor
Examples.Common/Examples.Common.csproj
NEW_CHANGELOG.md

- Add full screen state to configuration
- Fix 404 in example project in github pages, when reloading with a suburl
- Fix editor height regressions
- Fix resize parameter changes were ignored
- Fix visibility toggle broken in example
- Use Mod instead of Ctrl for shortcuts (Mac compatibility)

Height / fullscreen bugfixes

---

CHANGELOG.md
CodeMirror6/CodeMirror6.csproj
CodeMirror6/CodeMirror6WrapperInternal.razor.cs
CodeMirror6/NodeLib/src/index.ts
Examples.BlazorServer/Examples.BlazorServer.csproj
Examples.BlazorServerInteractive/Examples.BlazorServerInteractive.csproj
Examples.BlazorWasm/Examples.BlazorWasm.csproj
Examples.Common/Examples.Common.csproj
NEW_CHANGELOG.md

- Prevent null ref crashes
- Prevent setting any configs until the editor is initialized

🐛 Prevent null ref crashes

---

CHANGELOG.md
CodeMirror6/CodeMirror6.csproj
CodeMirror6/NodeLib/src/CmLogging.ts
Examples.BlazorServer/Examples.BlazorServer.csproj
Examples.BlazorServerInteractive/Examples.BlazorServerInteractive.csproj
Examples.BlazorWasm/Examples.BlazorWasm.csproj
Examples.Common/Examples.Common.csproj
NEW_CHANGELOG.md

Fix crash in logging

---

CHANGELOG.md
CodeMirror6/CodeMirror6.csproj
CodeMirror6/CodeMirror6Wrapper.razor
CodeMirror6/CodeMirror6Wrapper.razor.cs
CodeMirror6/CodeMirror6WrapperInternal.razor.cs
CodeMirror6/Models/CodeMirrorConfiguration.cs
CodeMirror6/NodeLib/src/CmConfiguration.ts
CodeMirror6/NodeLib/src/CmDiagrams.ts
CodeMirror6/NodeLib/src/CmHelpers.ts
CodeMirror6/NodeLib/src/CmId.ts
CodeMirror6/NodeLib/src/index.ts
Examples.BlazorServer/Examples.BlazorServer.csproj
Examples.BlazorServerInteractive/Examples.BlazorServerInteractive.csproj
Examples.BlazorWasm/Examples.BlazorWasm.csproj
Examples.Common/Example.razor
Examples.Common/Examples.Common.csproj
NEW_CHANGELOG.md

- Add ShowMarkdownControlCharactersAroundCursor parameter
- Update Microsoft to 8.0.2
- Improve local storage management
- Ensure correct aspect ratio of svg diagrams

 ✨ Add ShowMarkdownControlCharactersAroundCursor parameter

---

CHANGELOG.md
CodeMirror6/CodeMirror6.csproj
CodeMirror6/NodeLib/src/CmColumns.ts
CodeMirror6/NodeLib/src/CmKeymap.ts
CodeMirror6/NodeLib/src/index.ts
Examples.BlazorServer/Examples.BlazorServer.csproj
Examples.BlazorServerInteractive/Examples.BlazorServerInteractive.csproj
Examples.BlazorWasm/Examples.BlazorWasm.csproj
Examples.Common/Example.razor
Examples.Common/Examples.Common.csproj
NEW_CHANGELOG.md

- Support multiple cursors for arrow / shift / ctrl / ctrl-shift + arrow keys
- Add an example using ref

Support multiple cursors for arrow / shift / ctrl / ctrl-shift + arrow keys

---

CHANGELOG.md
CodeMirror6/CodeMirror6.csproj
CodeMirror6/NodeLib/src/CmColumns.ts
CodeMirror6/NodeLib/src/CmKeymap.ts
CodeMirror6/NodeLib/src/CmMentionsCompletion.ts
CodeMirror6/NodeLib/src/index.ts
Examples.BlazorServer/Examples.BlazorServer.csproj
Examples.BlazorServerInteractive/Examples.BlazorServerInteractive.csproj
Examples.BlazorWasm/Examples.BlazorWasm.csproj
Examples.Common/Examples.Common.csproj
NEW_CHANGELOG.md

- Support multiple cursors for (shift +) home & end keys
- Fix error when parsing TSV line with empty cell(s) at the end of the last row

✨ Support multiple cursors for (shift +) home & end keys

---

CHANGELOG.md
CodeMirror6/CodeMirror6.csproj
CodeMirror6/Models/CodeMirrorSimpleCommand.cs
CodeMirror6/NodeLib/src/CmInstance.ts
CodeMirror6/NodeLib/src/CmLint.ts
CodeMirror6/NodeLib/src/index.ts
Examples.BlazorServer/Examples.BlazorServer.csproj
Examples.BlazorServerInteractive/Examples.BlazorServerInteractive.csproj
Examples.BlazorWasm/Examples.BlazorWasm.csproj
Examples.Common/Example.razor
Examples.Common/Examples.Common.csproj
NEW_CHANGELOG.md

- Add a command to force linter update (#121)

✨ Add a command to force linter update (#121)

---

CHANGELOG.md
CodeMirror6/CodeMirror6.csproj
CodeMirror6/Models/CodeMirrorSetup.cs
CodeMirror6/NodeLib/src/CmSetup.ts
CodeMirror6/NodeLib/src/index.ts
Examples.BlazorServer/Examples.BlazorServer.csproj
Examples.BlazorServerInteractive/Examples.BlazorServerInteractive.csproj
Examples.BlazorWasm/Examples.BlazorWasm.csproj
Examples.Common/Examples.Common.csproj
NEW_CHANGELOG.md

- Add setup property FocusOnCreation
- Force scroll to start of document if not scrolling to end, on creation

Add setup property FocusOnCreation & Force scroll to start of document if not scrolling to end, on creation

---

CHANGELOG.md
CodeMirror6/CodeMirror6.csproj
CodeMirror6/NodeLib/src/CmImages.ts
Examples.BlazorServer/Examples.BlazorServer.csproj
Examples.BlazorServerInteractive/Examples.BlazorServerInteractive.csproj
Examples.BlazorWasm/Examples.BlazorWasm.csproj
Examples.Common/Examples.Common.csproj
NEW_CHANGELOG.md

- Ensure base path for images is read dynamically

🐛 Ensure base path for images is read dynamically

---

CHANGELOG.md
CodeMirror6/CodeMirror6.csproj
CodeMirror6/NodeLib/src/CmImages.ts
CodeMirror6/NodeLib/src/index.ts
Examples.BlazorServer/Examples.BlazorServer.csproj
Examples.BlazorServerInteractive/Examples.BlazorServerInteractive.csproj
Examples.BlazorWasm/Examples.BlazorWasm.csproj
Examples.Common/Examples.Common.csproj
NEW_CHANGELOG.md

- Fix initial setting of base link URLs for images, once more

🐛 Fix initial setting of base link URLs for images, once more

---

.config/dotnet-tools.json
CHANGELOG.md
CodeMirror6/CodeMirror6.csproj
Examples.BlazorServer/Examples.BlazorServer.csproj
Examples.BlazorServerInteractive/Examples.BlazorServerInteractive.csproj
Examples.BlazorWasm/Examples.BlazorWasm.csproj
Examples.Common/Examples.Common.csproj
NEW_CHANGELOG.md

Update nuget packages

---

CHANGELOG.md
CodeMirror6/CodeMirror6.csproj
Examples.BlazorServer/Examples.BlazorServer.csproj
Examples.BlazorServerInteractive/Examples.BlazorServerInteractive.csproj
Examples.BlazorWasm/Examples.BlazorWasm.csproj
Examples.Common/Examples.Common.csproj
NEW_CHANGELOG.md
make-release.sh

- Fix versioning
- Update changelog for 0.8.11

🐛 Fix versioning script

---

.gitignore
CHANGELOG.md
CodeMirror6/CodeMirror6.csproj
CodeMirror6/CodeMirror6WrapperInternal.razor
CodeMirror6/NodeLib/rollup.config.mjs
Examples.BlazorServer/Examples.BlazorServer.csproj
Examples.BlazorServerInteractive/Examples.BlazorServerInteractive.csproj
Examples.BlazorWasm/Examples.BlazorWasm.csproj
Examples.Common/Examples.Common.csproj
NEW_CHANGELOG.md
README.md

Relates to #187
- Add attribute `data-permanent` to container div
- Add FAQ about blazor server interactive
- Include JS source maps in release
- git ignore map files

Add attribute `data-permanent` to container div

---

.github/workflows/create-tag-and-deploy-on-merge-to-main.yml
.github/workflows/depoloy-on-tag.yml
.vscode/launch.json
CHANGELOG.md
CodeMirror6/CodeMirror6.csproj
Examples.BlazorServer/Examples.BlazorServer.csproj
Examples.BlazorServerInteractive/Examples.BlazorServerInteractive.csproj
Examples.BlazorWasm/Examples.BlazorWasm.csproj
Examples.Common/Examples.Common.csproj
NEW_CHANGELOG.md
README.md

🔖 Bump version to 0.9.1
